import Head from "next/head";
import Carousel from "../components/Carousel";
import MainLayout from "../layouts/MainLayout";
import SimpleCards from "../components/SimpleCards";
import UnconditionalHelp from "../components/UnconditionalHelp";
import Calendar from "../components/Calendar";
import Script from "next/script";

export default function Home() {
	return (
		<>
			<Head>
				<title>Humanitarian Inc.</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<MainLayout>
				<Carousel />
				<section id="content">
					<div className="content-wrap py-0" style={{ overflow: "visible" }}>
						<svg
							viewBox="0 0 1382 58"
							width="100%"
							height="60"
							preserveAspectRatio="none"
							style={{ position: "absolute", top: -58, left: 0, zIndex: 1 }}>
							<path
								style={{ fill: "#ffffff" }}
								d="M1.52.62s802.13,127,1380,0v56H.51Z"
							/>
						</svg>
						<div className="container">
							<div className="slider-feature w-100">
								<div className="row justify-content-center">
									<SimpleCards text="Education" icon="icon-line-align-center" />
									<SimpleCards text="Information" icon="icon-line-info" />
									<SimpleCards text="Help" icon="icon-line-help" />
								</div>
							</div>
						</div>
						<UnconditionalHelp />
						<Calendar />
					</div>
				</section>
			</MainLayout>
		</>
	);
}
